spring.application.name=20_UON_SOKVANNRITH_Spring003
spring.datasource.url=jdbc:postgresql://localhost:5433/spring
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver